//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _222_Goman_WPF_Project.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Goman_DB_Payment0Entities : DbContext
    {
        private static Goman_DB_Payment0Entities _context;
        public static Goman_DB_Payment0Entities GetContext()
        {
            if (_context == null)
            {
                _context = new Goman_DB_Payment0Entities();
            }
            return _context;
        }
        public Goman_DB_Payment0Entities()
            : base("name=Goman_DB_Payment0Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
